mysql:
  host: localhost
  port: 33067
  username: root
  password: root
  database: android_ios
  charset: utf8mb4
  parseTime: true
redis:
  host: localhost
  port: 13001
  password: ""
  db: 0
#oss:
#  Endpoint: "https://oss-cn-beijing.aliyuncs.com"
#  AccessKeyId: "LTAI5tG17fnfGpThU8nMMjyJ"
#  AccessKeySecret: "LruAAgiljPvOrxDaEh2ZYXACugxC2h"
#  Bucket: "xichen-server"
server: www.xichen.love