// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "phone_number 15294440097",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/send_email_code": {
            "post": {
                "description": "Send an email verification code to the specified email address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "公共方法"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email address to send the verification code to",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"msg\":\"验证码已经成功发送\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"msg\":\"请求参数错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"msg\":\"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/send_phone_code": {
            "post": {
                "description": "向指定手机号发送验证码。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "公共方法"
                ],
                "summary": "发送手机验证码",
                "parameters": [
                    {
                        "description": "接收验证码的手机号",
                        "name": "phone",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/servers.Basic"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "code\":201,\"msg\":\"验证码已经成功发送\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"msg\":\"请求无效。服务器无法理解请求\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"msg\":\"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/delete/address": {
            "post": {
                "description": "根据用户身份标识删除用户的地址信息。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户私有方法"
                ],
                "summary": "删除用户地址",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "要删除的地址身份标识",
                        "name": "identity",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\": 200, \"msg\": \"地址删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "code\": 400, \"msg\": \"请求无效。服务器无法理解请求\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "code\": 401, \"msg\": \"未授权\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "code\": 403, \"msg\": \"禁止访问\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "code\": 404, \"msg\": \"未找到资源\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "code\": 409, \"msg\": \"该账号没有被注册\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "code\": 500, \"msg\": \"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/get/avatar": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "从阿里云服务器获取用户头像，需要提供有效的用户身份验证令牌。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户私有方法"
                ],
                "summary": "获取用户头像",
                "parameters": [
                    {
                        "type": "string",
                        "default": "123",
                        "description": "Bearer {token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "code\": 400, \"msg\": \"请求错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "code\": 401, \"msg\": \"未授权\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "code\": 403, \"msg\": \"禁止访问\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "code\": 404, \"msg\": \"文件不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "code\": 500, \"msg\": \"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/get/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "解析用户信息，验证用户身份，并返回用户信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户私有方法"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\": 200, \"msg\": \"获取信息成功\", \"data\": {用户信息}}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "code\": 400, \"msg\": \"请求错误\"}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "401": {
                        "description": "code\": 401, \"msg\": \"未授权\"}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "404": {
                        "description": "code\": 404, \"msg\": \"用户不存在\"}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "409": {
                        "description": "code\": 409, \"msg\": \"该账号没有被注册\"}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "500": {
                        "description": "code\": 500, \"msg\": \"服务器内部错误\"}",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/user/login/password": {
            "post": {
                "description": "用户通过账号和密码进行登录，如果账号未注册、密码错误或其他错误将返回相应的错误信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "用户登录（密码）",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/servers.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\": \"200\", \"msg\": \"登录成功\", \"data\": {\"token\": \"用户token\"}}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "code\": \"400\", \"msg\": \"请求无效。服务器无法理解请求\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "code\": \"409\", \"msg\": \"该账号没有被注册\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "code\": \"500\", \"msg\": \"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login/phone": {
            "post": {
                "description": "用户通过手机号和验证码进行登录，如果手机号未注册、验证码错误或其他错误将返回相应的错误信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "用户登录（验证码）",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/servers.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\": \"200\", \"msg\": \"登录成功\", \"data\": {\"token\": \"用户token\"}}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "code\": \"400\", \"msg\": \"请求无效。服务器无法理解请求\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "code\": \"409\", \"msg\": \"该手机号没有被注册\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "code\": \"500\", \"msg\": \"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login/phone_and_password": {
            "post": {
                "description": "用户通过手机号和密码进行登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "用户登录（使用手机号和密码）",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/servers.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": \"200\", \"msg\": \"登录成功\", \"data\": {\"token\": \"jwt_token_here\"}}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{\"code\": 400, \"msg\": \"手机号或密码错误\"}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "401": {
                        "description": "{\"code\": 401, \"msg\": \"该手机号没有被注册\"}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "500": {
                        "description": "{\"code\": 500, \"msg\": \"服务器内部错误\"}",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/user/modify/info": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据提供的JSON请求体修改用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "修改用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "需要修改的用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/servers.User"
                        }
                    },
                    {
                        "maxLength": 6,
                        "type": "string",
                        "description": "验证码",
                        "name": "VerificationCode",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":200,\"msg\":\"修改信息成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"msg\":\"请求无效。服务器无法理解请求\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "code\":401,\"msg\":\"未授权\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "code\":403,\"msg\":\"请求错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "code\":404,\"msg\":\"该账号没有被注册\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "code\":409,\"msg\":\"请求错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "code\":500,\"msg\":\"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/register/phone": {
            "post": {
                "description": "用户通过手机号进行注册，如果手机号已存在或验证码错误将返回相应的错误信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户方法"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/servers.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\": \"200\", \"msg\": \"注册成功\", \"data\": {\"nickname\": \"用户昵称\", \"account\": \"用户账号\": \"\"}}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "code\": \"400\", \"msg\": \"请求无效。服务器无法理解请求\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "code\": \"409\", \"msg\": \"该手机号已经注册\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "code\": \"500\", \"msg\": \"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/upload/address": {
            "post": {
                "description": "通过解析用户信息和JSON请求体，将地址信息上传到用户信息中。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户私有方法"
                ],
                "summary": "向用户上传地址信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "要上传的地址信息,identity是不需要填写的，post_code可以写，也可以不写",
                        "name": "address",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/servers.AddressEntry"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\": 200, \"msg\": \"地址添加成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "code\": 400, \"msg\": \"请求无效。服务器无法理解请求\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "code\": 401, \"msg\": \"未授权\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "code\": 409, \"msg\": \"该账号没有被注册\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "code\": 500, \"msg\": \"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/uploads/avatar": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "处理用户上传头像的请求，需要提供有效的用户身份验证令牌。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户私有方法"
                ],
                "summary": "上传用户头像",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "用户头像文件",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\": 200, \"msg\": \"文件上传成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "code\": 400, \"msg\": \"请求错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "code\": 401, \"msg\": \"未授权\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "code\": 403, \"msg\": \"禁止访问\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "413": {
                        "description": "code\": 413, \"msg\": \"文件大小超出限制\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "code\": 500, \"msg\": \"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "servers.AddressEntry": {
            "type": "object",
            "properties": {
                "city": {
                    "description": "城市",
                    "type": "string"
                },
                "contact": {
                    "description": "联系人及其信息",
                    "type": "string"
                },
                "country": {
                    "description": "国家",
                    "type": "string"
                },
                "identity": {
                    "description": "唯一标识",
                    "type": "string"
                },
                "post_code": {
                    "description": "邮件地址",
                    "type": "string"
                },
                "province": {
                    "description": "省份",
                    "type": "string"
                },
                "street": {
                    "description": "街道",
                    "type": "string"
                }
            }
        },
        "servers.Basic": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "servers.User": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "address": {
                    "description": "地址列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/servers.AddressEntry"
                    }
                },
                "avatar": {
                    "description": "头像链接",
                    "type": "string"
                },
                "email": {
                    "description": "电子邮件",
                    "type": "string"
                },
                "file_base64": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "phone_number": {
                    "description": "电话号码",
                    "type": "string"
                },
                "score": {
                    "description": "评分",
                    "type": "integer"
                },
                "user_identity": {
                    "description": "用户身份信息",
                    "type": "string"
                },
                "verification_code": {
                    "description": "验证码",
                    "type": "string"
                },
                "wechat_number": {
                    "description": "微信号",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "192.168.0.146:13000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "淘牛马",
	Description:      "用于家畜交易",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
